feat: deploy DEV job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,6 +15,15 @@ permissions:
 
 
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: false
+
+
+
+
+
+
 env:
   ARTIFACTORY_DEV_USER: ${{ secrets.ARTIFACTORY_DEV_USER }}
   ARTIFACTORY_DEV_KEY: ${{ secrets.ARTIFACTORY_DEV_KEY }}
@@ -25,6 +34,8 @@ env:
   AWS_ACCOUNT_ID: 850756192530      # <- change to your AWS account id or set as repo var
   ECR_REPOSITORY: dwp/np/blog            # <- change to your ECR repository name
   #ECR_PUSH_ROLE: ${{ secrets.AWS_ECR_NONPROD_PUSH_ROLE }}
+  GIT_USER_NAME: "ci-bot"
+  GIT_USER_EMAIL: "ci-bot@devopswithprashant.com"
 
 
 
@@ -147,7 +158,57 @@ jobs:
           platforms: linux/amd64,linux/arm64
           tags: |
             ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
-            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ needs.maven.outputs.projectVersion }}
+            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ needs.maven.outputs.projectVersion }}-${{ github.sha }}
           # Optional: use GitHub Actions cache for build layers (fast incremental builds)
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+  
+  deploy-DEV:
+    needs: [maven, docker]
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+      - name: Checkout gitops repo
+        uses: actions/checkout@v4
+        with:
+          repository: "devopswithprashant/k8-blogApp"
+          token: ${{ secrets.GHEC_TOKEN_K8 }}
+          ref: main
+          fetch-depth: 10
+
+      - name: Update image tag in target file
+        #working-directory: gitops
+        id: update
+        env:
+          FILE: "apps/blog/dev/backend/blog-deployment.yaml"
+          IMAGE: "850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/np/blog"
+          NEW_TAG: ${{ needs.maven.outputs.projectVersion }}-${{ github.sha }}
+        run: |
+          set -euo pipefail
+          if [ ! -f "$FILE" ]; then
+            echo "ERROR target file not found: $FILE"
+            exit 1
+          fi
+          sed -i -E "s|(image:\s*850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/dwp/np/blog:)[^[:space:]]+|\1${NEW_TAG}|" "$FILE"
+          # Git config
+          git config user.name "${GIT_USER_NAME}"
+          git config user.email "${GIT_USER_EMAIL}"
+          # Check if file actually changed before committing
+          if git diff --quiet -- "$FILE"; then
+            echo "✅ No changes detected in $FILE — skipping commit & push."
+            exit 0
+          fi
+          git add "$FILE"
+          if git diff --cached --quiet; then
+            echo "✅ Nothing new to commit — skipping push."
+            exit 0
+          fi
+          git commit -m "chore(DEV): bump new version ${NEW_TAG} of blog image ${IMAGE}"
+          git push origin main
+
+      
+  
