test: release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -37,7 +37,7 @@ env:
 
 
 jobs:
-  maven-release:
+  maven:
     runs-on: ubuntu-latest
     outputs:
       projectVersion: ${{ steps.project_version.outputs.version }}
@@ -100,7 +100,7 @@ jobs:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v5
         with:
-          role-to-assume: ${{ secrets.AWS_ECR_NONPROD_PUSH_ROLE }}  # or use a secret: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+          role-to-assume: ${{ secrets.AWS_ECR_PROD_PUSH_ROLE }}  # or use a secret: ${{ secrets.AWS_ROLE_TO_ASSUME }}
           role-session-name: GitHubActionsECR
           aws-region: ${{ env.AWS_REGION }}
 
@@ -130,56 +130,56 @@ jobs:
           platforms: linux/amd64,linux/arm64
           tags: |
             ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
-            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ needs.maven.outputs.projectVersion }}-${{ github.sha }}
+            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:v${{ needs.maven.outputs.projectVersion }}
           # Optional: use GitHub Actions cache for build layers (fast incremental builds)
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
   
-  deploy-DEV:
-    needs: [maven, docker]
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-    steps:
-    # Checkout the repository to the GitHub Actions runner
-      - name: Checkout gitops repo
-        uses: actions/checkout@v4
-        with:
-          repository: "devopswithprashant/k8-blogApp"
-          token: ${{ secrets.GHEC_TOKEN_K8 }}
-          ref: ${{ github.ref }}
-          fetch-depth: 10
+  # deploy-DEV:
+  #   needs: [maven, docker]
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   steps:
+  #   # Checkout the repository to the GitHub Actions runner
+  #     - name: Checkout gitops repo
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: "devopswithprashant/k8-blogApp"
+  #         token: ${{ secrets.GHEC_TOKEN_K8 }}
+  #         ref: ${{ github.ref }}
+  #         fetch-depth: 10
 
-      - name: Update image tag in target file
-        #working-directory: gitops
-        id: update
-        env:
-          FILE: "apps/blog/dev/backend/blog-deployment.yaml"
-          IMAGE: "850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/np/blog"
-          NEW_TAG: ${{ needs.maven.outputs.projectVersion }}-${{ github.sha }}
-        run: |
-          set -euo pipefail
-          if [ ! -f "$FILE" ]; then
-            echo "ERROR target file not found: $FILE"
-            exit 1
-          fi
-          sed -i -E "s|(image:\s*850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/dwp/np/blog:)[^[:space:]]+|\1${NEW_TAG}|" "$FILE"
-          # Git config
-          git config user.name "${GIT_USER_NAME}"
-          git config user.email "${GIT_USER_EMAIL}"
-          # Check if file actually changed before committing
-          if git diff --quiet -- "$FILE"; then
-            echo "✅ No changes detected in $FILE — skipping commit & push."
-            exit 0
-          fi
-          git add "$FILE"
-          if git diff --cached --quiet; then
-            echo "✅ Nothing new to commit — skipping push."
-            exit 0
-          fi
-          git commit -m "chore(DEV): bump new version ${NEW_TAG} of blog image ${IMAGE}"
-          git push origin ${{ github.ref }}
+  #     - name: Update image tag in target file
+  #       #working-directory: gitops
+  #       id: update
+  #       env:
+  #         FILE: "apps/blog/dev/backend/blog-deployment.yaml"
+  #         IMAGE: "850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/np/blog"
+  #         NEW_TAG: ${{ needs.maven.outputs.projectVersion }}-${{ github.sha }}
+  #       run: |
+  #         set -euo pipefail
+  #         if [ ! -f "$FILE" ]; then
+  #           echo "ERROR target file not found: $FILE"
+  #           exit 1
+  #         fi
+  #         sed -i -E "s|(image:\s*850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/dwp/np/blog:)[^[:space:]]+|\1${NEW_TAG}|" "$FILE"
+  #         # Git config
+  #         git config user.name "${GIT_USER_NAME}"
+  #         git config user.email "${GIT_USER_EMAIL}"
+  #         # Check if file actually changed before committing
+  #         if git diff --quiet -- "$FILE"; then
+  #           echo "✅ No changes detected in $FILE — skipping commit & push."
+  #           exit 0
+  #         fi
+  #         git add "$FILE"
+  #         if git diff --cached --quiet; then
+  #           echo "✅ Nothing new to commit — skipping push."
+  #           exit 0
+  #         fi
+  #         git commit -m "chore(DEV): bump new version ${NEW_TAG} of blog image ${IMAGE}"
+  #         git push origin ${{ github.ref }}
 
       
